name: jotter_mapper
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Path and Instances 
  get_it: ^7.7.0
  go_router: ^14.2.0

  # Assets and Themes
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10+1

  # Miscellaneous
  path_provider: ^2.1.3
  smooth_page_indicator: ^1.1.0
  form_field_validator: ^1.1.0
  cupertino_icons: ^1.0.8
  firebase_core: ^3.1.1
  flutter_dotenv: ^5.1.0
  shared_preferences: ^2.2.3
  firebase_auth: ^5.1.1
  google_sign_in: ^6.2.1
  flutter_spinkit: ^5.2.1
  cloud_firestore: ^5.0.2
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  change_app_package_name: ^1.2.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - .env
