name: jotter_mapper
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Path and Instances 
  get_it: ^7.7.0
  go_router: ^14.2.0

  # Assets and Themes
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10+1

  # Miscellaneous
  path_provider: ^2.1.3
  smooth_page_indicator: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
